### ISSUE TITLE
Error al eliminar un registro

### ISSUE THREAD

**Issue by geronm12** [wolfagus/proyecto-final-front#28]
Buenos días chicos, les subo un issue que encontré en el proyecto. 

Situación: Un usuario registrado como administrador elimina un registro de cualquiera de las tablas que se encuentran en el sistema (pedidos, menu, usuarios) y el registro se elimina correctamente pero no se refresca el componente.

**### Resultado esperado**

 Al eliminar un registro se deberá refrescar el componente para poder mostrar los datos reales al usuario.

**### Prerequisitos**
Estar loggeado como usuario administrador.
Email: lautaroansaloni47@gmail.com
Password: Maria123

![image](https://user-images.githubusercontent.com/44532299/225022847-600cee58-5413-4417-a59a-e19996b1ec94.png)
 

https://user-images.githubusercontent.com/44532299/225023585-6dedf9f9-57c7-4744-8b27-47dec901ff09.mp4

### **Posible Fix**

Verificar el useEffect que se encarga de traer los datos de la base de datos, probablemente agregando a las dependencias el array de datos traidos del servidor resuelva el error.

**Comment by LautaroAnsaloni** [comment]
Hola Gero! Como va?
El componente se refresca al eliminar el usuario. En el video se puede notar que en ese usuario que borras cambia la fecha de eliminación.
No borramos del todo al usuario para seguir viendo sus datos. Hacemos solo un soft delete, mostrando la fecha de eliminacion y modificando a true el "isDelete" en la DB de Mongo. Al menos es como lo estuvimos laburando en clase. 
Vos haces referencia a borrar toda la fila de ese usuario en la tabla?

Desde ya te agradezco el tiempo y laburo por corregirnos. +100 puntos por el video!

**Comment by geronm12** [comment]
Lautaro, tenes razón.  Está perfecto lo del soft delete, no me había percatado de la fecha de eliminación. 
 A modo consejo por ahí a la hora de eliminar podrían diferenciar los registros ya eliminados de los que están activos más que nada porque si bien la fecha de eliminación está perfecta por ahí puede pasar desapercibida. Podrían usar el mismo booleano de isDelete para mostrarlo en una columna de la grilla y ponerle una máscara como "Activo" o "Inactivo" y cambiar el color de la celda o de la fuente entre rojo y verde para que esa info está resaltada. Otra cosa sería no poder eliminar dos veces un mismo objeto de las base pero nuevamente estos sólo son consejos. No hace falta que hagan esos cambios. Cierro el issue.
